Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,6 +15,24 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: |
+          set -x
+
+          if [[ "$GITHUB_REF_PROTECTED" != 'true' ]]; then
+            echo 'Deployment to production is only allowed from a protected ref'
+            exit 1
+          fi
+
+          BEFORE_SHA="$(cat $GITHUB_EVENT_PATH | jq -r .before)"
+          if [[ "${#BEFORE_SHA}" != 40 ]]; then
+            echo 'Unable to determine before-SHA'
+            exit 1
+          fi
+          
+          if [[ "$BEFORE_SHA" != '0000000000000000000000000000000000000000' ]]; then
+            echo 'Deployment to production is not allowed from the initial commit for a protected ref'
+            exit 1
+          fi
+      - run: |
           printenv | sort
       - run: echo "$GITHUB_CONTEXT"
         env:
