Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,20 +6,20 @@ jobs:
     runs-on: self-hosted
     steps:
 #      - run: rm -rf /home/runner/work/testing/testing/runner/_layout/_diag
-      - id: thesuccessstep
+      - id: the_success
         run: echo the success
-  #    - { run: "echo \"$STEPS\"", env: { STEPS: "${{ toJson(steps) }}" } }
-   #   - id: the_success_bc_continue_on_error
-    #    run: echo 'success bc continue on error' ; exit 1
-     #   continue-on-error: true
-      #- { run: "echo \"$STEPS\"", env: { STEPS: "${{ toJson(steps) }}" } }
-#      - id: the_cancelled
- #       run: echo 'cancelled!' ; ping -c 100 127.0.0.1
-  #      timeout-minutes: 1
-   #   - { run: "echo \"$STEPS\"", env: { STEPS: "${{ toJson(steps) }}" } }
-    #  - id: the_skipped
-     #   run: echo 'skipped!'
-      #- { if: "always()", run: "echo \"$STEPS\"", env: { STEPS: "${{ toJson(steps) }}" } }
+      - { run: "echo \"$STEPS\"", env: { STEPS: "${{ toJson(steps) }}" } }
+      - id: the_success_bc_continue_on_error
+        run: echo 'success bc continue on error' ; exit 1
+        continue-on-error: true
+      - { run: "echo \"$STEPS\"", env: { STEPS: "${{ toJson(steps) }}" } }
+      - id: the_cancelled
+        run: echo 'cancelled!' ; ping -c 100 127.0.0.1
+        timeout-minutes: 1
+      - { run: "echo \"$STEPS\"", env: { STEPS: "${{ toJson(steps) }}" } }
+      - id: the_skipped
+        run: echo 'skipped!'
+      - { if: "always()", run: "echo \"$STEPS\"", env: { STEPS: "${{ toJson(steps) }}" } }
 
 
 
